language: node_js
node_js:
- node
- 10
- 13
before_install: npm --global install greenkeeper-lockfile
before_script:
- greenkeeper-lockfile-update
- npm --version
after_script: greenkeeper-lockfile-upload
install: yarn install
script: yarn test
cache:
  yarn: true
  directories:
  - node_modules
